### Test quotes put without login 
POST http://localhost:3001/api/quotes 
Content-Type: application/json

{
    "serviceItem": [
        {
            "item": "LawnMow",
            "unit": 23,
            "whatUnit": "Hours",
            "pricePerUnit": 12,
            "otherComment": "Very tough evn plug $20",
            "otherCost": 20
        }
    ],
}

### create client
POST http://localhost:3001/api/clients
Content-Type: application/json

{
    "username":"byf",
    "password":"123",
    "name":"yifan"
}

### Test quotes get
DELETE http://localhost:3003/api/quotes/6118b3473e24400cb803f343



###  create quote
POST http://localhost:3001/api/quotes 
Content-Type: application/json

{
    "serviceItem": [
        {
            "item": "LawnMow",
            "unit": 123,
            "whatUnit": "Hours",
            "pricePerUnit": 12,
            "otherComment": "Very tough evn plug $20",
            "otherCost": 20
        }
    ],
    "comment" : "lalala2",
    "userId" : "612e40e2f339e773e5e6ab2a"
}

### user login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "byf",
    "password": "123"
}

### post with token

POST http://localhost:3001/api/quotes 
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJ5ZiIsImlkIjoiNjEyZTQwZTJmMzM5ZTc3M2U1ZTZhYjJhIiwiaWF0IjoxNjMwNDIxMzA4fQ.Xa5budF5YgfcK3ZwA8V89yW13iV8Z0dSFYerYe-oebs

{
    "serviceItem": [
        {
            "item": "Maaaaaaaaa",
            "unit": 0.22,
            "whatUnit": "Hours",
            "pricePerUnit": 12,
            "otherComment": "Very tough evn plug $20",
            "otherCost": 20
        }
    ],
    "userId" : "612e4a3fde601e80b9f1344a"
}



### create a guest client
POST http://localhost:3003/api/guests 
Content-Type: application/json

{
    "name": "test-name",
    "address": "test-addr",
    "phone": "test phone",
    "email": "3@sd.com"
}

### login 
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"byf",
    "password":"123"
}


### guest post
POST http://localhost:3001/api/guests 
Content-Type: application/json

{
    "name":"sadasd",
    "address" : "asdasdasdas"
}