### Test quotes put without login 
POST http://localhost:3001/api/bookings 
Content-Type: application/json

{
    "serviceItem": [
        {
            "item": "LawnMow",
            "unit": 23,
            "whatUnit": "Hours",
            "pricePerUnit": 12,
            "otherComment": "Very tough evn plug $20",
            "otherCost": 20
        }
    ],
}

### Test quotes get
DELETE http://localhost:3003/api/quotes/6118b3473e24400cb803f343


### user login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "123",
    "password": "123"
}

### post with token

POST http://localhost:3001/api/quotes 
Content-Type: application/json
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IjEyMyIsImlkIjoiNjEyZWVhOTFmNDY3YWEyZmUxYzkzNGQzIiwiaWF0IjoxNjMwNDY3MTE5fQ.kJhS88MP8pkjDfMdMDHsCNwJ_OgoSfo7KImFNo5f4Ck

{
    "serviceItem": [
        {
            "item": "Maaaaaaaaa",
            "unit": 0.22,
            "whatUnit": "Hours",
            "pricePerUnit": 12,
            "otherComment": "Very tough evn plug $20",
            "otherCost": 20
        }
    ],
    "comment" :"my test"
}



### create a guest client
POST http://localhost:3003/api/guests 
Content-Type: application/json

{
    "name": "test-name",
    "address": "test-addr",
    "phone": "test phone",
    "email": "3@sd.com"
}

### login 
POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username":"byf",
    "password":"123"
}


### guest post
POST http://localhost:3001/api/guests 
Content-Type: application/json

{
    "name":"sadasd",
    "address" : "asdasdasdas"
}

### admin regeist
POST http://localhost:3001/api/admin/register 
Content-Type: application/json

{
    "username":"admin",
    "password" : "admin"
}

### admin login
POST http://localhost:3001/api/admin/login 
Content-Type: application/json

{
    "username":"admin",
    "password" : "admin"
}

### create new user
POST http://localhost:3001/api/bookings 
Content-Type: application/json
Authorization: bearer eyJhbGciOiJSUzI1NiIsImtpZCI6ImFlNTJiOGQ4NTk4N2U1OWRjYWM2MmJlNzg2YzcwZTAyMDcxN2I0MTEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYXV0aC1kZXYtNTNjOWIiLCJhdWQiOiJhdXRoLWRldi01M2M5YiIsImF1dGhfdGltZSI6MTYzMjQ0NTM5NSwidXNlcl9pZCI6ImRmTkx2MVdRMVVaRUw3MW5KMUpsRlhybm5pbzIiLCJzdWIiOiJkZk5MdjFXUTFVWkVMNzFuSjFKbEZYcm5uaW8yIiwiaWF0IjoxNjMyNDQ5MzIzLCJleHAiOjE2MzI0NTI5MjMsImVtYWlsIjoiMTIzQDEyMy5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiMTIzQDEyMy5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.AEnc_xv3pOcgKwEMOneJTdND7mSnV-SMRe-PeRqzl0dyoMjXGnaJ0jc21VYkoZStsVFLlKihOUSqG4eKM3nnQddjsagt39PWXUT_xAA4BC0PSAqCgPof8NTeSmxjbOOaQmRMDOFmyJAefGruDnnkNRCL7Dg8oBldLgtBCm-By7KiZNBUMqLUyVUcE7t3P6Jc4W1bPOJ-tAWngHt_cOdvKUu_P5tScsaK-cD5WECISl7KmiVMzduXhAekr36YCNGIlJUOJumkeBmccl2HRPFsCg90705jokSsGxYNx6DRPDg1XyqWibvdvbk6MJ7ZXpPqxkvVuwRe_k3cb1XMlfED5A

{
    "address": "123 rd"
}